# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\":\n\x0e\x43ommandRequest\x12(\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x17.controller.CommandType\" \n\x0f\x43ommandResponse\x12\r\n\x05value\x18\x01 \x01(\x05*B\n\x0b\x43ommandType\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x12\t\n\x05\x41NGLE\x10\x02\x12\t\n\x05SPEED\x10\x03\x12\x08\n\x04STOP\x10\x04\x32\\\n\x10\x44\x65viceController\x12H\n\x0bSendCommand\x12\x1a.controller.CommandRequest\x1a\x1b.controller.CommandResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=126
  _globals['_COMMANDTYPE']._serialized_end=192
  _globals['_COMMANDREQUEST']._serialized_start=32
  _globals['_COMMANDREQUEST']._serialized_end=90
  _globals['_COMMANDRESPONSE']._serialized_start=92
  _globals['_COMMANDRESPONSE']._serialized_end=124
  _globals['_DEVICECONTROLLER']._serialized_start=194
  _globals['_DEVICECONTROLLER']._serialized_end=286
# @@protoc_insertion_point(module_scope)
